CREATE OR REPLACE TABLE PROPERTY (
    PROPERTY_ID INT,
    ADDRESS STRING,
    CITY STRING
);

CREATE OR REPLACE TABLE ROOM (
    ROOM_ID INT,
    PROPERTY_ID INT,
    ROOM_TYPE STRING
);

CREATE OR REPLACE TABLE INSPECTION_NOTE (
    NOTE_ID INT,
    ROOM_ID INT,
    TEXT STRING
);

CREATE OR REPLACE TABLE IMAGE_METADATA (
    IMAGE_ID INT,
    ROOM_ID INT,
    LABEL STRING,
    CONFIDENCE FLOAT
);
