CREATE OR REPLACE TABLE DEFECTS AS
SELECT
    r.PROPERTY_ID,
    t.ROOM_ID,
    t.DEFECT,
    t.CONFIDENCE
FROM TEXT_DEFECTS t
JOIN ROOM r ON t.ROOM_ID = r.ROOM_ID

UNION ALL

SELECT
    r.PROPERTY_ID,
    i.ROOM_ID,
    i.LABEL AS DEFECT,
    i.CONFIDENCE
FROM IMAGE_METADATA i
JOIN ROOM r ON i.ROOM_ID = r.ROOM_ID;
